theme = "semi-native"

icons = "awesome5"

[[block]]
block = "focused_window"
max_width = 30
show_marks = "visible"

[[block]]
block = "disk_space"
path = "/"
info_type = "used"
format = "{icon} {available} free"
alert_absolute = true
unit = "GB"
alert = 150
warning = 140

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization} {frequency}"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average} avg"
chip = "*-isa-*"

[[block]]
block = "backlight"

[[block]]
block = "hueshift"
hue_shifter = "redshift"
step = 50
click_temp = 3500

[[block]]
block = "sound"

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]

#[[block]]
#block = "networkmanager"
#on_click = "alacritty -e nmtui"
#interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]

[[block]]
block = "networkmanager"
on_click = "alacritty -e nmtui"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []
ap_format = "{ssid^10}"

#[[block]]
#block = "pomodoro"
#length = 25
#break_length = 5
#message = "Take a break!"
#break_message = "Back to work!"
##notifier = "swaynag"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m/%Y %R"

[[block]]
block = "battery"
interval = 10
format = " {percentage} {time}"
full_format = " "
